### ISSUE TITLE
Initial review notes

### ISSUE THREAD

**Issue by abea** [apostrophecms-legacy/apostrophe-secure-attachments#2]
- [x] These TODOs are likely to get lost. Better added as issues. https://github.com/apostrophecms/apostrophe-secure-attachments/blob/master/index.js#L78-L85
- [x] Are these `trash(null).published(null)` referencing defaults?
- [x] This comment could be clearer: https://github.com/apostrophecms/apostrophe-secure-attachments/blob/master/index.js#L102
- [ ] When I secure an image as "login required" I can't see that in an index page where it appeared anymore, but I _can_ view it at the direct URL received via "View File." I had the same results with a PDF.
- [ ] [This is unclear](https://github.com/apostrophecms/apostrophe-secure-attachments/blob/master/lib/modules/apostrophe-secure-attachments-files/index.js#L5) since it's looking at file permissions but references pages.
- [x] I added an image to a page, made that page "login required" and then visited another page where that image appears while logged out. I was still able to view the photo on the accessible page.
- [ ] I think we should mark a new module like this as in beta (`2.0.0-beta`) until battle tested.
- [ ] I thought that only secure files would be routed through the middleware, taking the perf hit. This looks like every upload will be.

**Comment by abea** [comment]
Checking off the page one since that's not a requirement.

**Comment by boutell** [comment]
* TODOs in code: are now issues.
* `trash(null).published(null)`: by default you don't get trashed and unpublished things because you usually don't want them. For this module, you need to get everything you are allowed to get. Members of the public still won't get trashed or unpublished things because they *cannot* get them, we're just expressing a *desire* to include them and not bypassing any permission checks.
* "This comment could be clearer": which comment?
* "When I secure an image as login required and visit another page where that image appears while logged out..." I could not duplicate this. I think perhaps the image *itself* was not secured via its own permissions and you were trying to secure it via the page permissions, which is a different beast entirely (see below).
* Confusing leftover comment about pages: removed.
* Making a *page* "login required" has *nothing to do* with the permissions of a *file or image*. You must set the permissions of the *file or image*. I think this will be intuitive to people whose heads are not full of our earlier, confusing attempts to rationalize doing it the other way round, which is extremely difficult to implement and does not meet the client's need ("this PDF should not ever be public, period, I don't care what page somebody thinks they want to put it on").
* I don't think we should mark this as beta, it's not a practice we have followed so far. We are shipping it to a customer for production use. We should test it, of course, and fix bugs if they are found. The software is under the MIT license which makes clear there is no warranty.
* All uploads are routed through the middleware, yes, this is documented. It is a necessary tradeoff, otherwise it would take many more person-hours to implement. We can work on that optimization if there is interest from an enterprise client who needs the performance and the security in the same site, but intranets are generally not requested as part of very large, high-traffic sites. They are separate use cases.

**Comment by abea** [comment]
The unclear comment moved when other changes were made. I was referring to the "No sneakiness" one.
